In [242]:
import pandas as pd
import numpy as np

In [243]:
Date = pd.read_csv('orders.csv')
Time = pd.read_csv('messages.csv')

In [244]:
Date.head(5)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [245]:
Time.head(5)

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [246]:
Date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [247]:
Time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [248]:
Date['date'] = pd.to_datetime(Date['date'])

In [249]:
Date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [250]:
Date['date_year'] = Date['date'].dt.year

In [251]:
Date.sample(5)

          date  product_id  city_id  orders  date_year
869 2018-12-30        2542        0       2       2018
813 2019-06-12          12       25       1       2019
351 2018-12-23        2056       28       1       2018
905 2018-08-22         133       16       2       2018
146 2019-12-13        6828       13       1       2019

In [252]:
Date['date_month_number'] = Date['date'].dt.month

In [253]:
Date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_number
962 2018-09-10        2220        2      99       2018                  9
12  2019-03-15        5665        5       1       2019                  3
801 2018-12-17         630       10      12       2018                 12
481 2019-02-16        1115       30       1       2019                  2
875 2018-11-01        4495       28       1       2018                 11

In [254]:
Date['date_month_number'] = Date['date'].dt.month_name()
Date.sample(5)

          date  product_id  city_id  orders  date_year date_month_number
237 2019-12-09        5489       13      23       2019          December
92  2019-05-30        5788        7      34       2019               May
28  2019-04-20        5501       16       1       2019             April
930 2018-09-06        6716       16       4       2018         September
70  2019-10-29        6443       16       1       2019           October

In [255]:
Date['day_of_the_month'] = Date['date'].dt.day
Date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month
755,2019-07-07,4457,22,30,2019,July,7
560,2018-08-04,358,10,15,2018,August,4
404,2019-07-12,841,0,2,2019,July,12
968,2019-02-12,754,18,1,2019,February,12
457,2019-10-12,4347,25,195,2019,October,12

In [256]:
Date['day_of_week'] = Date['date'].dt.dayofweek
Date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week
691,2019-06-22,1917,0,2,2019,June,22,5
739,2019-08-06,1673,13,2,2019,August,6,1
738,2019-05-27,7585,27,2,2019,May,27,0
200,2019-02-06,3449,28,5,2019,February,6,2
540,2018-09-26,7350,16,23,2018,September,26,2

In [257]:
Date['day_name'] = Date['date'].dt.day_name()
Date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week,day_name
32,2018-10-23,2845,23,1,2018,October,23,1,Tuesday
337,2019-07-15,4180,16,1,2019,July,15,0,Monday
649,2019-02-05,6976,22,19,2019,February,5,1,Tuesday
754,2019-05-03,2323,25,122,2019,May,3,4,Friday
445,2019-10-14,4192,14,59,2019,October,14,0,Monday

In [258]:
Date['date_is_weekend'] = np.where(Date['day_name'].isin(['Sunday', 'Saturday']), 1,0)
Date.drop(columns=['product_id','city_id','orders']).head()
Date.head(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week,day_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,January,6,6,Sunday,1

In [259]:
Date['week_ofthe_year'] = Date['date'].dt.week
Date.sample(5)

/var/folders/56/x3z_k92d2gbdk0b5qtg5p95h0000gn/T/ipykernel_29300/834639487.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  Date['week_ofthe_year'] = Date['date'].dt.week

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week,day_name,date_is_weekend,week_ofthe_year
945,2018-07-17,2568,22,8,2018,July,17,1,Tuesday,0,29
16,2019-04-10,977,22,1,2019,April,10,2,Wednesday,0,15
348,2019-02-09,1848,14,135,2019,February,9,5,Saturday,1,6
367,2018-12-18,3678,13,1,2018,December,18,1,Tuesday,0,51
262,2018-11-14,4667,9,1,2018,November,14,2,Wednesday,0,46

In [260]:
Date['quarter_ofthe_year'] = Date['date'].dt.quarter
Date.drop(columns=['product_id','city_id','orders']).head()
Date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week,day_name,date_is_weekend,week_ofthe_year,quarter_ofthe_year
513,2019-10-30,6975,3,3,2019,October,30,2,Wednesday,0,44,4
796,2019-07-12,5393,9,1,2019,July,12,4,Friday,0,28,3
298,2018-12-12,3748,17,11,2018,December,12,2,Wednesday,0,50,4
34,2019-04-09,4185,18,12,2019,April,9,1,Tuesday,0,15,2
444,2019-07-24,6115,22,29,2019,July,24,2,Wednesday,0,30,3

In [261]:
Date['semester'] = np.where(Date['quarter_ofthe_year'].isin([1,2]), 1, 2)
Date.drop(columns=['product_id','city_id','orders']).head()
Date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,day_of_the_month,day_of_week,day_name,date_is_weekend,week_ofthe_year,quarter_ofthe_year,semester
144,2019-10-14,5778,24,108,2019,October,14,0,Monday,0,42,4,2
748,2019-01-12,920,14,1,2019,January,12,5,Saturday,1,2,1,1
464,2018-09-26,4895,29,1,2018,September,26,2,Wednesday,0,39,3,2
250,2019-02-16,2611,13,11,2019,February,16,5,Saturday,1,7,1,1
230,2018-07-22,7554,13,12,2018,July,22,6,Sunday,1,29,3,2

In [262]:
import datetime
today = datetime.datetime.today
today()

datetime.datetime(2026, 4, 1, 0, 43, 33, 152100)

In [263]:
today() - Date['date']

0     2304 days 00:43:33.158568
1     2786 days 00:43:33.158568
2     2717 days 00:43:33.158568
3     2419 days 00:43:33.158568
4     2642 days 00:43:33.158568
                 ...
995   2732 days 00:43:33.158568
996   2673 days 00:43:33.158568
997   2521 days 00:43:33.158568
998   2586 days 00:43:33.158568
999   2360 days 00:43:33.158568
Name: date, Length: 1000, dtype: timedelta64[ns]

In [264]:
(today() - Date['date']).dt.days

0      2304
1      2786
2      2717
3      2419
4      2642
       ...
995    2732
996    2673
997    2521
998    2586
999    2360
Name: date, Length: 1000, dtype: int64

In [265]:
np.round((today() - Date['date']) / np.timedelta64(1, 'M'),0)

0      76.0
1      92.0
2      89.0
3      79.0
4      87.0
       ...
995    90.0
996    88.0
997    83.0
998    85.0
999    78.0
Name: date, Length: 1000, dtype: float64

#Time

In [266]:
Time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [267]:
Time['date'] = pd.to_datetime(Time['date'])

In [268]:
Time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
Time['hour'] = Time['date'].dt.hour
Time['min'] = Time['date'].dt.minute
Time['sec'] = Time['date'].dt.second

Time.head(10)

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
5,2016-03-08 22:52:00,пар.32прок.дев.на авто по ночн.городу.Днепр.06...,22,52,0
6,2014-02-18 00:23:00,Семейная пара познакомится для отношений,0,23,0
7,2012-11-23 01:10:00,ДЛЯ С.П СНАЧАЛО СМС 066.679.400.8,1,10,0
8,2014-12-23 01:20:00,Дедушки ау вы где? СНЕГУРОЧКИ СКУЧАЮТ. Здесь е...,1,20,0
9,2012-11-03 23:46:00,ищу парня с авто.063 528 90 72,23,46,0

In [272]:
Time['time'] = Time['date'].dt.time
Time.head(5)

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [274]:
today() - Time['date']

0     4489 days 23:55:49.486814
1     4354 days 01:05:49.486814
2     4840 days 00:24:49.486814
3     4142 days 00:14:49.486814
4     4539 days 01:34:49.486814
                 ...
995   5128 days 23:55:49.486814
996   4450 days 01:31:49.486814
997   4915 days 01:08:49.486814
998   5031 days 01:11:49.486814
999   4303 days 01:20:49.486814
Name: date, Length: 1000, dtype: timedelta64[ns]

In [275]:
(today() - Time['date']) / np.timedelta64(1, 's')

0      3.879358e+08
1      3.761896e+08
2      4.181776e+08
3      3.578698e+08
4      3.921754e+08
           ...
995    4.431454e+08
996    3.844856e+08
997    4.246602e+08
998    4.346828e+08
999    3.717841e+08
Name: date, Length: 1000, dtype: float64

In [276]:
(today() - Time['date']) / np.timedelta64(1, 'm')

0      6.465597e+06
1      6.269827e+06
2      6.969626e+06
3      5.964496e+06
4      6.536256e+06
           ...
995    7.385757e+06
996    6.408093e+06
997    7.077670e+06
998    7.244713e+06
999    6.196402e+06
Name: date, Length: 1000, dtype: float64

In [278]:
(today() - Time['date']) / np.timedelta64(1, 'h')

0      107759.962870
1      104497.129537
2      116160.446204
3       99408.279537
4      108937.612870
           ...
995    123095.962870
996    106801.562870
997    117961.179537
998    120745.229537
999    103273.379537
Name: date, Length: 1000, dtype: float64